# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: XIII Workshop on Agents Applied in Healthcare (A2HC2021)
email: stefano.mariani@unimore.it
description: >- # this means to ignore newlines until "baseurl:"
  Home page for the XIII Workshop on Agents Applied in Healthcare (A2HC2021)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  A2HC2021
repository: "A2HC2021/a2hc2021.github.io"

# Build settings
markdown: kramdown
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "mint" # aqua
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true

search: true
timezone: Europe/Rome

author:
  name        : "Stefano Mariani"
  avatar      : "/assets/images/sm.jpg"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:stefano.mariani@unimore.it"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://personale.unimore.it/rubrica/dettaglio/s.mariani"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/stemarO_O"
