# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: XIII Workshop on Agents Applied in Healthcare (A2HC2021)
email: stefano.mariani@unimore.it
description: >- # this means to ignore newlines until "baseurl:"
  The workshop aims to discuss applications of agent technologies into healthcare, a crucial domain of research, as demonstrated by the numerous initiatives devoted to financially supporting projects in this topic, such as those included under the “Health and Wellbeing” work programme of H2020 in Europe or promoted by the NIH in USA. They particularly motivate research devoted to finding solutions enabling an effective introduction of ICT in healthcare, since it is expected to have a big impact in expanding healthcare coverage while reducing its costs. Topics like Healthy Ageing, Active Living, Chronic Diseases or others related to Quality of Life play an increasingly important role in research.
Besides these long-standing efforts, the recent global health situation caused by the COVID-19 pandemy both strengthened existing motivations for a digital transformation in healthcare and brought along new ones, by urging medical practitioners to embrace digital tools for delivering care to patients, and medical organisations and administrators to optimise resource usages as never before.
To overcome these new difficulties and deal with the long-standing ones as well, many technical issues have yet to be addressed, with the goal of providing medical practitioners at any organisational level (primary care, intensive care, administrators, etc.) the most suitable digital tools to support their day to day practice, introducing telemedicine to rethink processes and organisation of healthcare facilities. Clinical decision support systems, adaptive and intelligent workflow management software, personal digital assistants, wearable technology ecosystems and the like are all tools with enormous potential benefits to deliver in the healthcare domain, for instance.
Intelligent agent-based systems constitute one of the most exciting research areas in Artificial Intelligence. Due to the growing interest in the application of agent-based systems in healthcare, a number of applications addressing clinical problems are already based on agent technology. Thus, it is unquestionable that a benefit is guaranteed if the specialists in the field can meet and report on the results achieved in this area, discuss the advantages that agent-based systems may bring to medical domains, and possibly the problems they encountered, and also provide a list of the research topics that should be tackled in the near future.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  A2HC2021

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
